var dontOptions = [
  { value: "", label: "Option 可不選" },
  { value: "please don't be too long or too short.", label: "不要過長或過短 (be too long or too short)" },
  { value: "please don't plagiarize or be too rough.", label: "不要剽竊或過於粗糙 (plagiarize or be too rough)" },
  { value: "please don't be too complex or too simple.", label: "不要太複雜或太簡單 (be too complex or too simple)" },
  { value: "please don't be too boring or too funny.", label: "不要太無聊或太滑稽 (be too boring or too funny)" },
  { value: "please don't be too subjective or too objective.", label: "不要太主觀或太客觀 (be too subjective or too objective)" },
  { value: "please Don't do {thing}", label: "不要做{事情} (Don't do {thing})" },
  { value: "please Avoid {thing}, please.", label: "請避免{事情} (Avoid {thing}, please)" },
  { value: "please Restrict that {action}", label: "限制{行為} (Restrict that {action})" },
  { value: "please Disallow that {action}", label: "禁止{行為} (Disallow that {action})" },
  { value: "please Refrain from {action}", label: "禁止{操作} (Refrain from {action})" },
  { value: "please No, don't do {action}", label: "不，不要{行動} (No, don't do {action})" },
  { value: "please Avoid that {behavior}", label: "避免{行為} (Avoid that {behavior})" },
  { value: "please You should not {action}", label: "你不應該{行為} (You should not {action})" },
  { value: "please Stay clear of {action}", label: "遠離{行為} (Stay clear of {action})" },
  { value: "please Don't engage in {action}", label: "不要參與{行動} (Don't engage in {action})" },
  { value: "other", label: "其它 other" },
];