var formats = [
    { value: "", label: "Option 可不選" },
    { value: "input the final result in a Plain text.", label: "純文字(Plain text)" },
    { value: "input the final result in a JSON.", label: "JSON(JSON)" },
    { value: "input the final result in a JSON-LD.", label: "JSON-LD" },
    { value: "input the final result in a Markdown.", label: "Markdown" },
    { value: "input the final result in a HTML.", label: "HTML 超文本標記語言" },
    { value: "tell me the story in Emojis.", label: "表情圖(Emoji)" },
    { value: "input the final result in a CSV.", label: "CSV" },
    { value: "input the final result in a XML.", label: "XML" },
    { value: "input the final result in a PDF.", label: "PDF" },
    { value: "input the final result in a Image.", label: "影像(Image)" },
    { value: "input the final result in a Audio.", label: "聲音的(Audio)" },
    { value: "input the final result in a Video.", label: "視頻(Video)" },
    { value: "input the final result in a Excel.", label: "Excel" },
    { value: "input the final result in a PowerPoint.", label: "PowerPoint" },
    { value: "input the final result in a Word.", label: "Word" },
    { value: "input the final result in a LaTex.", label: "LaTex" },
    { value: "input the final result in a GIF.", label: "動圖(GIF)" },
    { value: "input the final result in a SVG.", label: "SVG" },
    { value: "input the final result in a RTF.", label: "RTF" },
    { value: "input the final result in a YAML.", label: "YAML" },
    { value: "input the final result in a Binary.", label: "二進位(Binary)" },
    { value: "input the final result in a Tabular.", label: "表格(Tabular)" },
    { value: "input the final result in a RSS.", label: "RSS" },
    { value: "input the final result in a ZIP.", label: "ZIP" },
    { value: "input the final result in a TAR.", label: "TAR" },
    { value: "input the final result in a SQL.", label: "SQL" },
    { value: "input the final result in a JavaSeript.", label: "Java腳本(JavaSeript)" },
    { value: "input the final result in a CSV.", label: "CSV" },
    { value: "input the final result in a MP3.", label: "MP3" },
    { value: "input the final result in a WAV.", label: "WAV" },
    { value: "input the final result in a MP4.", label: "MP4" }
  ];