var roles = [
  { value: "You are Dr.Know everything", label: "指定一個角色 Role" },
  { value: "an Expert Accountant", label: "專家會計師(Expert Accountant)" },
  { value: "a Skilled Doctor", label: "熟練的醫生(Skilled Doctor)" },
  { value: "a senior judge", label: "資深法官(Senior judge)" },
  { value: "a Profieient Lawyer", label: "資深律師(Profieient Lawyer)" },
  { value: "a Skilled Software Developer", label: "熟練的軟體開發人員(Skilled Software Developer)" },
  { value: "a Seasoned Teacher", label: "經驗豐富的老師(Seasoned Teacher)" },
  { value: "an Accomplished Sales Representative", label: "優秀的銷售代表(Accomplished Sales Representative)" },
  { value: "a Competent Project Manager", label: "稱職的專案經理(Competent Project Manager)" },
  { value: "a Qualified Engineer", label: "合格工程師(Qualified Engineer)" },
  { value: "an Experienced Architeet", label: "經驗豐富的建築師(Experienced Architeet)" },
  { value: "a Competent Marketing Manager", label: "稱職的營銷經理(Competent Marketing Manager)" },
  { value: "a Knowledgeable Financial Analyst", label: "知識淵博的金融分析師(Knowledgeable Financial Analyst)" },
  { value: "a Creative Graphie Designer", label: "創意平面設計師(Creative Graphie Designer)" },
  { value: "a Trusted Consultant", label: "值得信賴的顧問(Trusted Consultant)" },
  { value: "a Licensed Psychologist", label: "執業心理學家(Licensed Psychologist)" },
  { value: "a Dedicated Researcher", label: "專職研究員(Dedicated Researcher)" },
  { value: "an Analytical Data Analyst", label: "分析資料分析師(Analytical Data Analyst)" },
  { value: "an Astute Economist", label: "精明的經濟學家(Astute Economist)" },
  { value: "a Journalistic Reporter", label: "新聞記者(Journalistic Reporter)" },
  { value: "a Professional Pharmacist", label: "專業藥劑師(Professional Pharmacist)" },
  { value: "a Compassionate Soeial Worker", label: "富有同情心的社會工作者(Compassionate Soeial Worker)" },
  { value: "a Tech-savvy IT Specialist", label: "精通科技的 IT 專家(Tech-savvy IT Specialist)" },
  { value: "an Insightful Business Analyst", label: "富有洞察力的業務分析師(Insightful Business Analyst)" },
  { value: "a Seasoned Operations Manager", label: "經驗豐富的營運經理(Seasoned Operations Manager)" },
  { value: "a Strategie Event Planner", label: "策略活動策劃師(Strategie Event Planner)" },
  { value: "an Expert Real Estate Agent", label: "專業房地產經紀人(Expert Real Estate Agent)" },
  { value: "a Seasoned Investment Banker", label: "經驗豐富的投資銀行家(Seasoned Investment Banker)" },
  { value: "a Proficient Web Developer", label: "熟練的網頁開發人員(Proficient Web Developer)" },
  { value: "a Certified Fitness Trainer", label: "認證健身教練(Certified Fitness Trainer)" },
  { value: "a Professional Executive Coach", label: "專業執行教練(Professional Executive Coach)" },
  { value: "an Agile Scrum Master", label: "敏捷專案管理大師(Agile Scrum Master)" },
  { value: "a Cybersecurity Analyst", label: "網路安全分析師(Cybersecurity Analyst)" },
  { value: "an User Experience (UX) Researcher", label: "使用者體驗 (UX) 研究員(User Experience (UX) Researcher)" },
  { value: "a Blockchain Developer", label: "區塊鏈開發者(Blockchain Developer)" },
  { value: "an Artificial Intelligence AI Engineer", label: "人工智慧AI工程師(Artificial Intelligence AI Engineer)" },
  { value: "an Environmental Consultant", label: "環境顧問(Environmental Consultant)" },
  { value: "a Data Privaey Officer", label: "資料隱私官(Data Privaey Officer)" },
  { value: "a Virtual Reality (VR) Developer", label: "虛擬實境 (VR) 開發人員(Virtual Reality (VR) Developer)" },
  { value: "an Ethical Hacker", label: "道德駭客(Ethical Hacker)" },
  { value: "Walter Isaacson", label: "華特·艾薩克森 賈伯斯傳作者(Walter Isaacson)" },
  { value: "Steve Jobs", label: "賈伯斯(Steve Jobs)" },
  { value: "a poet", label: "一個詩人(a poet)" },
  { value: "a storyteller", label: "說故事的人(a storyteller)" },
  { value: "a coder", label: "程式設計師(a coder)" },
  { value: "a teacher", label: "一個老師(a teacher)" },
  { value: "a chatbot", label: "一個聊天機器人(a chatbot)" },
  { value: "other", label: "其它(other)" },
];