var tasks = [
  { value: "{任務 Task}", label: "任務 Task" },
  { value: "Summarize", label: "總結(Summarize)" },
  { value: "Predict", label: "預測(Predict)" },
  { value: "Optimize", label: "最佳化(Optimize)" },
  { value: "Translate", label: "翻譯(Translate)" },
  { value: "Calculate", label: "計算(Calculate)" },
  { value: "Analyze", label: "分析(Analyze)" },
  { value: "Distinguish", label: "辨別(Distinguish)" },
  { value: "Diagnose", label: "診斷(Diagnose)" },
  { value: "Recommend", label: "推薦(Recommend)" },
  { value: "Identify", label: "確認(Identify)" },
  { value: "Generate", label: "產生(Generate)" },
  { value: "Classify", label: "分類(Classify)" },
  { value: "Validate", label: "證實(Validate)" },
  { value: "Simulate", label: "模擬(Simulate)" },
  { value: "Detect", label: "探測(Detect)" },
  { value: "Convert", label: "轉變(Convert)" },
  { value: "Recognize", label: "認出(Recognize)" },
  { value: "Personalize", label: "個人化(Personalize)" },
  { value: "Rank", label: "排名(Rank)" },
  { value: "Automate", label: "自動化(Automate)" },
  { value: "Monitor", label: "監視器(Monitor)" },
  { value: "Customize", label: "客製化(Customize)" },
  { value: "Enhance", label: "提高(Enhance)" },
  { value: "Discover", label: "發現(Discover)" },
  { value: "Streamline", label: "精簡(Streamline)" },
  { value: "Adapt", label: "適應(Adapt)" },
  { value: "Stream", label: "溪流(Stream)" },
  { value: "Filter", label: "篩選(Filter)" },
  { value: "Track", label: "追蹤(Track)" },
  { value: "Plan", label: "計劃(Plan)" },
  { value: "Design", label: "設計(Design)" },
  { value: "Collaborate", label: "合作(Collaborate)" },
  { value: "Debug", label: "除錯(Debug)" },
  { value: "Improve", label: "提升(Improve)" },
  { value: "Review from books I've read", label: "從我讀過的書中複習 Review from books I've read" },
  { value: "use my own words and knowledge", label: "使用我自己的話和知識 use my own words and knowledge" },
  { value: "use predefined tools and data", label: "使用預先定義的工具和資料 use predefined tools and data" },
  { value: "use external sources and references", label: "使用外部資源和參考資料 use external sources and references" },
  { value: "use user feedback and input", label: "使用使用者回饋和輸入 use user feedback and input" },
  { value: "use creative and innovative methods", label: "使用創意和創新方法 use creative and innovative methods" },
  { value: "other", label: "其它 other" }
];